# Generated by Django 2.2.19 on 2022-09-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220908_1637'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientamount',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='ingredientamount',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='pair ingredient/recipe must be unique'),
        ),
    ]
