# Generated by Django 2.2.19 on 2022-09-10 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20220909_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcartitem',
            old_name='client',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='recipe_to_cart',
        ),
        migrations.AddField(
            model_name='shoppingcartitem',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_to_cart', to='recipes.Recipe', verbose_name='recipe to cart'),
            preserve_default=False,
        ),
    ]
