# Generated by Django 2.2.19 on 2022-09-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20220911_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(unique=True, verbose_name='recipe description'),
        ),
    ]
