# Generated by Django 2.2.19 on 2022-09-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20220911_1758'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shoppingcartitem',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='user can add recipe to shopping cart just once'),
        ),
    ]
